version: "3.8"
name: docker-usbscan

services:

    dev:
        image: docker-usbscan-dev:${IMG_TAG:-latest}
        container_name: docker-usbscan-dev
        build:
            context: .
            dockerfile: ./docker/dev.dockerfile      
            #args:
            #    NODE_VERSION: 20.9.0

        privileged: true # This is required to access USB devices from the docker container
        #user: ${CUR_UID:-1000:1000} # This is required in order to access host's filesystem from the docker container
        user: root
        # cap_add:
        #     - SYS_ADMIN
        #     - DAC_READ_SEARCH
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        env_file:
            - ${ENV_FILE_PATH:-env/.dev.env}
        ports:
            - "${HOST_SERVER_PORT:-3000}:${SERVER_PORT:-3000}"            
        volumes:
            - ~/.bash_history:/home/node/.bash_history
            - ./workspace:/home/node/workspace
            - /dev:/dev
            - /media:/media

    prod:
        image: docker-usbscan-prod:${IMG_TAG:-latest}
        container_name: docker-usbscan-prod
        env_file:
            - ${ENV_FILE_PATH:-env/.prod.env}
        build:
            context: .
            dockerfile: ./docker/prod.dockerfile
        ports:
            - "${HOST_PORT:-3001}:${PORT:-3001}"
        volumes:
            - ./logs:/home/node/logs
        
        
# Commands

# PREPARE
# Set envfile path:    > export ENV_FILE_PATH=<env file path>

# BUILD
# - Build:             > docker compose build
# - Build with args:   > docker compose build --build-arg NODE_VERSION="16.14.2"
# - Build Clean:       > docker compose build --no-cache

# RUN DEV CONTAINER
# - Run Dev:           > docker compose run --service-ports --rm dev bash
# - Run Dev with env:  > ENV_FILE_PATH=./env/.dev.env docker compose run --rm dev bash

# RUN PROD
# - Run with rm:       > docker compose run --rm prod 
# - Run :              > docker compose up 
# - Run envfile:       > docker compose --env-file $ENV_FILE_PATH
# - Stop Rel:          > docker compose down
